// SPDX-License-Identifier: LGPL-3.0-only
// Copyright (c) 2026 Attila Agas
// Auto-generated by scripts/gen_schema_enums.py — do not edit directly.
// Regenerate: cmake --build <build-dir> --target gen_schema_enums
#pragma once
#include <array>
#include <string_view>

namespace UDisplaySchema {

constexpr std::array<std::string_view, 3> kButtonShapes = {"rect", "circle", "square"};
constexpr std::array<std::string_view, 2> kButtonGroupLayouts = {"grid", "dpad"};
constexpr std::array<std::string_view, 2> kTextModes = {"ro", "rw"};
constexpr std::array<std::string_view, 2> kDisplayStyles = {"default", "large"};
constexpr std::array<std::string_view, 3> kLabelStyles = {"heading", "body", "caption"};

} // namespace UDisplaySchema
