#!/usr/bin/env python3
"""Generate udisplay_schema_enums.h from udisplay.schema.json.

Usage: gen_schema_enums.py <schema.json> <output.h>
"""
import json
import sys
from pathlib import Path


def get_enum(defs, widget_key, field):
    w = defs.get(widget_key, {})
    return w.get("properties", {}).get(field, {}).get("enum", [])


def array_literal(values):
    items = ", ".join(f'"{v}"' for v in values)
    return f"{{{items}}}"


def main():
    if len(sys.argv) != 3:
        sys.exit(f"Usage: {sys.argv[0]} <schema.json> <output.h>")

    schema_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    with open(schema_path) as f:
        schema = json.load(f)

    defs = schema.get("$defs", {})

    button_shapes    = get_enum(defs, "buttonWidget",      "shape")
    bg_layouts       = get_enum(defs, "buttonGroupWidget", "layout")
    text_modes       = get_enum(defs, "textWidget",        "mode")
    display_styles   = get_enum(defs, "displayWidget",     "style")
    label_styles     = get_enum(defs, "labelWidget",       "style")

    lines = [
        "// SPDX-License-Identifier: LGPL-3.0-only",
        "// Copyright (c) 2026 Attila Agas",
        "// Auto-generated by scripts/gen_schema_enums.py — do not edit directly.",
        "// Regenerate: cmake --build <build-dir> --target gen_schema_enums",
        "#pragma once",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace UDisplaySchema {",
        "",
        f"constexpr std::array<std::string_view, {len(button_shapes)}> "
        f"kButtonShapes = {array_literal(button_shapes)};",
        f"constexpr std::array<std::string_view, {len(bg_layouts)}> "
        f"kButtonGroupLayouts = {array_literal(bg_layouts)};",
        f"constexpr std::array<std::string_view, {len(text_modes)}> "
        f"kTextModes = {array_literal(text_modes)};",
        f"constexpr std::array<std::string_view, {len(display_styles)}> "
        f"kDisplayStyles = {array_literal(display_styles)};",
        f"constexpr std::array<std::string_view, {len(label_styles)}> "
        f"kLabelStyles = {array_literal(label_styles)};",
        "",
        "} // namespace UDisplaySchema",
        "",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
